language: java
jdk:
  - oraclejdk7
  - openjdk7
 
before_install:
 - chmod +x gradlew

script: ./gradlew build
#sudo: false # faster builds

#after_success:
# - bash <(curl -s https://codecov.io/bash)
